### ISSUE TITLE
Customization of .cocoapods.yml file does not work

### ISSUE THREAD

**Issue by DenHeadless** [CocoaPods/cocoapods-try#40]
It does not seem like .cocoapods.yml customization file is working right now

[repo with yml file](https://github.com/DenHeadless/DTModelStorage/blob/master/.cocoapods.yml)
```bash
pod try DTModelStorage
```

output:
```
Updating spec repositories
Trying DTModelStorage
Opening '/private/var/folders/fb/wfd_w9kn7bqf86gm9dpk0wg40000gn/T/CocoaPods/Try/DTModelStorage/DTModelStorageTests/DTModelStorage.xcworkspace'
```

There's no echo message and git submodules did not get updated. I tried with suggested example

```
pod try ORStackView
```
and it doesn't seem like it prints anything.

versions: 
cocoapods-try 0.50.1
cocoapods (0.38.2)

Maybe i'm missing something?

//cc @orta

**Comment by orta** [comment]
Yeah, the last stable release does not contain the `pod try` commands: https://github.com/CocoaPods/CocoaPods/blob/0.38.2/cocoapods.gemspec - you'd need to be using the beta for it to work  https://github.com/CocoaPods/cocoapods-try/blob/master/CHANGELOG.md

But as you're using `0.5.1` I did a quick look. I don't think you have the right yaml syntax:

``` yaml
try:
    install:
    pre:
        - echo "DTModelStorage tests require Nimble.framework, updating git submodules..."
        - git submodule update --init --recursive
```

as yam is whitespace dependent, this should work:

``` yaml
try:
    install:
      pre:
        - echo "DTModelStorage tests require Nimble.framework, updating git submodules..."
        - git submodule update --init --recursive

```
